### ISSUE TITLE
Formatting of tiles on index.html

### ISSUE THREAD

**Issue by gnsmith** [Niels-Bohr-Institute-XNS-StructBiophys/ArlethGroupWebsite#14]
![screenshot 2019-01-17 at 10 25 39](https://user-images.githubusercontent.com/46593797/51308367-3e7c2d80-1a42-11e9-87a0-08ccdaed200e.png)

Tiles look good, but I saw a few issues.

- There is inconsistent bordering on them. My preference would be no borders (a la industry collaboration).
- Looking again, I think they could also do with some internal bordering as well. Basically more spacing so that they are not right on the edge.
- Finally there is a character between the tiles horizontally, and I don't know why. It renders as a something like an underscore between the two pairs of tiles.

**Comment by proteinchemist** [comment]
Ah, yes. I will take a look at it. I really don't know where the underscore-like character comes from, and any suggestions are welcome :-)

**Comment by gnsmith** [comment]
I tried looking in the HTML, and I couldn't see anything.

As an alternative, you could centre the coloured tile on a white background to create the padding? And then remove the padding in the HTML. So the white edges would touch each other, but the coloured squares would not.

I'll see if I can work out something about the underscore.

**Comment by gnsmith** [comment]
Problem solved:

https://stackoverflow.com/questions/9003969/underscore-between-two-image-links

**Comment by gnsmith** [comment]
Take the spaces out of the <a> </a> tabs.

**Comment by gnsmith** [comment]
I'll do this by the way, so you can leave it for me.

**Comment by proteinchemist** [comment]
Hahaha, wonderful! Nice! Let me know if you need me to do anything.

**Comment by gnsmith** [comment]
Problem solved. 👌
